apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-demo

resources:
- fastapi-deployment.yaml
- fastapi-service.yaml
- fastapi-configmap.yaml

images:
- name: maguero22/lucymar-api
  newTag: 3c65095
